name: DataFrameTest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Download raw data
      run: |
        wget https://kelvins.esa.int/media/public/competitions/collision-avoidance-challenge/train_data.zip
        unzip train_data.zip
        cp train_data.csv data/
        ls -lh 
        ls -lh data/
        head --lines 20000 data/train_data.csv > data/train_data.csv
        wc -l data/train_data.csv       
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest test_dataframe_creation.py